# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chase Gruber - Web Developer
email: chasegruber@gmail.com
description: > 
  Data-visualizing, map-making web developer based in Washington, D.C.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: CPGrubes
github_username:  cpgruber
# Build settings
markdown: kramdown
